### ISSUE TITLE
[EPIC] detected fields UX tweaks

### ISSUE THREAD

**Issue by matryer** [grafana/logs-drilldown#395]
```[tasklist]
### Tasks
- [x] https://github.com/grafana/explore-logs/issues/393
- [x] https://github.com/grafana/explore-logs/issues/398
- [ ] #401
- [x] Loading state: When Detected fields is first loading, the page looks broken. We could add a spinner and hide the field bar.
```

<img width="1261" alt="image" src="https://github.com/grafana/explore-logs/assets/101659/cea309e7-bb4f-45c8-9df2-ce7b9a156ccd">

**Comment by zizzpudding** [comment]
consider skeleton loading for these. 
https://www.nngroup.com/articles/skeleton-screens/
